language: java

jdk:
  - oraclejdk8

sudo: false # faster builds
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)  
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
